// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ToggleSolenoid.h"
#include "Commands/z_TemplateCommand.h"
#include "Commands/z_TemplateSequence.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joystick1 = new Joystick(0);
	
//	z_ButtonTemplate = new JoystickButton(joystick1, 16);
//	z_ButtonTemplate->WhenPressed(new ToggleSolenoid());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("z_TemplateCommand", new z_TemplateCommand());

	SmartDashboard::PutData("z_TemplateSequence", new z_TemplateSequence());

	//SmartDashboard::PutData("ToggleSolenoid", new ToggleSolenoid());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	m_button1 = new JoystickButton(joystick1, 1);
	m_button1->WhenPressed(new ToggleSolenoid(0));

	m_button2 = new JoystickButton(joystick1, 2);
	m_button2->WhenPressed(new ToggleSolenoid(1));

	m_button3 = new JoystickButton(joystick1, 3);
	m_button3->WhenPressed(new ToggleSolenoid(2));

	m_button4 = new JoystickButton(joystick1, 4);
	m_button4->WhenPressed(new ToggleSolenoid(3));

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getJoystick1() {
	return joystick1;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
