// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::subsystem1SpeedController1 = NULL;
SpeedController* RobotMap::subsystem1SpeedController2 = NULL;
RobotDrive* RobotMap::subsystem1RobotDrive21 = NULL;
Compressor* RobotMap::compressorSubSystemWaveCompressor = NULL;
Solenoid* RobotMap::pneumaticsTesterSolenoid0 = NULL;
Solenoid* RobotMap::pneumaticsTesterSolenoid1 = NULL;
Solenoid* RobotMap::pneumaticsTesterSolenoid2 = NULL;
Solenoid* RobotMap::pneumaticsTesterSolenoid3 = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	subsystem1SpeedController1 = new Talon(0);
	lw->AddActuator("Subsystem 1", "Speed Controller 1", (Talon*) subsystem1SpeedController1);
	
	subsystem1SpeedController2 = new Talon(1);
	lw->AddActuator("Subsystem 1", "Speed Controller 2", (Talon*) subsystem1SpeedController2);
	
	subsystem1RobotDrive21 = new RobotDrive(subsystem1SpeedController1, subsystem1SpeedController2);
	
	subsystem1RobotDrive21->SetSafetyEnabled(true);
        subsystem1RobotDrive21->SetExpiration(0.1);
        subsystem1RobotDrive21->SetSensitivity(0.5);
        subsystem1RobotDrive21->SetMaxOutput(1.0);
        

	compressorSubSystemWaveCompressor = new Compressor(0);
	
	
	pneumaticsTesterSolenoid0 = new Solenoid(0, 0);
	lw->AddActuator("PneumaticsTester", "Solenoid 0", pneumaticsTesterSolenoid0);
	
	pneumaticsTesterSolenoid1 = new Solenoid(0, 1);
	lw->AddActuator("PneumaticsTester", "Solenoid 1", pneumaticsTesterSolenoid1);
	
	pneumaticsTesterSolenoid2 = new Solenoid(0, 2);
	lw->AddActuator("PneumaticsTester", "Solenoid 2", pneumaticsTesterSolenoid2);
	
	pneumaticsTesterSolenoid3 = new Solenoid(0, 3);
	lw->AddActuator("PneumaticsTester", "Solenoid 3", pneumaticsTesterSolenoid3);
	


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
